version: "3"

services:
  
  loki: 
    image: grafana/loki:2.4.1
    ports:
      - "3100:3100"
    
  grafana:
    image: grafana/grafana:8.2.3
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
        
  jaeger:
    image: jaegertracing/all-in-one:1.28
    ports:
      - "16686:16686"  # Jaeger UI
      - "6831:6831/udp"