{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /events
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.name }}-backend
                port:
                  name: http 
          - path: /api
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.name }}-backend
                port:
                  name: http 
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.name }}-frontend
                port:
                  name: http 
{{- end }}
